FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY server.js ./
COPY package.json ./
EXPOSE 3000
ENTRYPOINT ["node"]
CMD ["server.js", "development"]
